mongodb:
  host: "cluster0.urikuvt.mongodb.net"
  userKey: "MONGODB_USERNAME"
  pwdKey: "MONGODB_PASSWORD"
  db: "emozis"
  collection: "project"
  backup_path: "./data/mongodb_backup.json"

table:
  category:
    type: TextColumn
    label: "분류"
    width: "small"
  start_date:
    type: DateColumn
    label: "시작 일시"
    width: "small"
    format: "YYYY/MM/DD"
  end_date:
    type: DateColumn
    label: "종료 일시"
    width: "small"
    format: "YYYY/MM/DD"
  content:
    type: TextColumn
    label: "내용"
    width: "medium"
  status:
    type: TextColumn
    label: "진행상황"
    width: "small"